// Consent registry — canonical text for each consent kind, version bumps when
// wording changes, and helpers to record + look up user acceptance.
//
// Acceptance is recorded to users/{uid}/consents/{id}. Every tap creates a new
// record so the history survives version changes. `text_hash` gives us a
// tamper-evident audit trail without storing the full text on every doc.

import type { Consent, ConsentKind, MedicalCondition, Injury } from './types'
import { saveConsentRecord, listConsentRecords } from './storage'

export const CONSENT_VERSIONS: Record<ConsentKind, string> = {
  general_ai: 'v1-2026-07-02',
  chronic_condition: 'v1-2026-07-02',
}

export const CONSENT_TITLES: Record<ConsentKind, string> = {
  general_ai: 'Before we start',
  chronic_condition: 'One more thing about your health',
}

export const CONSENT_ACCEPT_LABELS: Record<ConsentKind, string> = {
  general_ai: 'I understand and agree',
  chronic_condition: 'I understand and will consult my doctor',
}

// Presented as a bullet list. Keep each line short and plain-English.
export const CONSENT_BULLETS: Record<ConsentKind, string[]> = {
  general_ai: [
    "GymBuddy is an AI fitness coach for general fitness guidance — not a medical service.",
    "Plans are generated by an AI model and are intended for beginners in normal health.",
    "I will stop any exercise that causes pain, dizziness, or unusual symptoms.",
    "I will consult a licensed doctor or physiotherapist before starting if I have any doubts about my fitness to exercise, and during the program if new symptoms appear.",
    "Nutrition suggestions are general food ideas, not a prescribed medical diet.",
    "I have given honest information about my body, injuries, and health.",
  ],
  chronic_condition: [
    "You told us about a chronic health condition (e.g. heart condition, high blood pressure, diabetes, asthma, or pregnancy).",
    "GymBuddy will build a lower-intensity plan for you, but AI cannot replace a doctor's clearance.",
    "I will speak with my doctor or specialist before starting this program.",
    "I will follow any restrictions my doctor has already given me — including movements or intensities to avoid.",
    "I will stop and seek medical help if I feel pain, dizziness, chest pressure, breathing difficulty, or any unusual symptom.",
    "I understand GymBuddy is not a medical device and does not diagnose or treat any condition.",
  ],
}

// Non-cryptographic hash (djb2). Enough to detect wording drift; not a password.
function hashText(text: string): string {
  let h = 5381
  for (let i = 0; i < text.length; i++) {
    h = ((h << 5) + h) + text.charCodeAt(i)
    h |= 0
  }
  return Math.abs(h).toString(36)
}

export function textHashFor(kind: ConsentKind): string {
  const body = [CONSENT_TITLES[kind], ...CONSENT_BULLETS[kind]].join('\n')
  return hashText(body)
}

export interface RecordConsentArgs {
  kind: ConsentKind
  medical_conditions: MedicalCondition[]
  injuries: Injury[]
}

export async function recordConsent(args: RecordConsentArgs): Promise<Consent> {
  return saveConsentRecord({
    kind: args.kind,
    version: CONSENT_VERSIONS[args.kind],
    accepted: true,
    accepted_at: new Date().toISOString(),
    medical_conditions_at_accept: args.medical_conditions,
    injuries_at_accept: args.injuries,
    text_hash: textHashFor(args.kind),
  })
}

export async function hasCurrentConsent(kind: ConsentKind): Promise<boolean> {
  const version = CONSENT_VERSIONS[kind]
  const all = await listConsentRecords()
  return all.some((c) => c.kind === kind && c.version === version && c.accepted)
}

export function requiresChronicConsent(conditions: MedicalCondition[]): boolean {
  return conditions.some((c) => c !== 'none')
}
